name: Engine indexer connector test

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/-tests.yml"
      - ".github/actions/compile_and_test/action.yml"
      - ".github/actions/indexer_connector_deps/action.yml"
      - "src/engine/source/indexerconnector/**"
      - "src/engine/source/wazuh-http-request/**"
env:
  BUILD_PRESET: ${{ github.event.inputs.build_preset || 'release' }}
  ENGINE_DIR: ${{github.workspace}}/src/engine

jobs:
  indexer_connector-qa:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{env.ENGINE_DIR}}/vcpkg'
          vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
          vcpkgJsonGlob: '${{env.ENGINE_DIR}}/vcpkg.json'
    
      - name: Configure CMake
        run: cmake --preset=${{env.BUILD_PRESET}} --no-warn-unused-cli -S ${{env.ENGINE_DIR}}
  
      - name: Build
        run: cmake --build ${{env.ENGINE_DIR}}/build --target indexer_connector_tool -j$(nproc)

      # Install python dependencies
      - name: Install dependencies
        run: |
          pip install -r ${{env.ENGINE_DIR}}/source/indexerconnector/qa/requirements.txt

      # Create folder for test logs
      - name: Create folder for test logs
        run: |
          mkdir -p ${{ github.workspace }}/qa_logs

      # Run indexer connector tests.
      - name: Run tests
        run: |
          cd src
          python -m pytest -vv engine/source/indexerconnector/qa/ --log-cli-level=DEBUG
          rm -rf tmp

      # Upload log files of the tests
      - name: Upload log files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: QA log files
          path: ${{ github.workspace }}/qa_logs
